name: App build

on:
  push:
    branches:
      - main
jobs:
  build_and_release:
    runs-on: macos-14

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: authenticate with github package registry
        run: npm set "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}"
      - run: npm ci
      - run: npm run dist
